#! /bin/bash
echo "Setting up iptables rules.."

echo "Flushing current rules.."
iptables -F

echo "Blocking null packets.."
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

echo "Rejecting syn flood attack.."
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

echo "Rejecting xmas packets.."
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

echo "Saving new rules.."
service iptables save
